version: '2.2'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 6080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user1
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      db:
      condition: service_healthy      

  db:
    image: mysql:5.7
    restart: always
    environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD >> /var/lib/mysql/health.log
        test: ls -ld /var/lib/mysql/wordpress >> /var/lib/mysql/health.log 
        #volumes:
            #test: CMD ["/bin/sh", "-c", "test -f /var/lib/mysql/wordpress > ./db/health.log 2>&1"]
        #wordpress:
        #db:
